#!/usr/bin/env python3
"""Generate docs/compatibility.md by probing every registered service with the
server's OWN liveness logic. Doubles as a large-scale integration test.

Run:  python scripts/compat_matrix.py
"""

from __future__ import annotations

import asyncio
import json
from collections import Counter
from datetime import datetime, timezone

from ga4gh_mcp.cache import TTLCache
from ga4gh_mcp.config import Settings
from ga4gh_mcp.http import AsyncHttp
from ga4gh_mcp.registry import RegistryClient
from ga4gh_mcp.serviceinfo import probe_liveness


async def main() -> None:
    settings = Settings()
    http = AsyncHttp(timeout=settings.request_timeout, max_retries=1)
    registry = RegistryClient(settings.registry_url, http, TTLCache())

    services = await registry.services()
    implementations = await registry.implementations()
    types = await registry.service_types()

    sem = asyncio.Semaphore(12)

    async def probe(svc):
        async with sem:
            if not svc.url:
                return svc, {"liveness": "no_url", "reachable": False}
            res = await probe_liveness(http, svc.url, svc.artifact, timeout=settings.probe_timeout)
            return svc, res

    probed = await asyncio.gather(*(probe(s) for s in services))
    await http.close()

    verdicts = Counter(r["liveness"] for _, r in probed)
    artifacts = Counter((s.artifact or "unknown") for s, _ in probed)

    rows = []
    for svc, res in sorted(probed, key=lambda x: ((x[0].artifact or ""), x[0].name or "")):
        rows.append({
            "artifact": svc.artifact,
            "name": svc.name,
            "org": svc.organization.name if svc.organization else None,
            "declared": svc.type.version if svc.type else None,
            "reported": res.get("reported_version"),
            "liveness": res.get("liveness"),
            "auth": "yes" if res.get("auth_required") else "",
            "url": svc.url,
        })

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = []
    lines.append("# GA4GH Implementation Registry — Compatibility Matrix\n")
    lines.append(f"_Auto-generated by `scripts/compat_matrix.py` on {ts} using the server's own "
                 f"liveness logic against `{settings.registry_url}`._\n")
    lines.append(f"- **Services (live deployments):** {len(services)}")
    lines.append(f"- **Implementations (codebases):** {len(implementations)}")
    lines.append(f"- **Distinct service types:** {len(types)}\n")

    lines.append("## Liveness verdicts\n")
    lines.append("| Verdict | Count | Meaning |")
    lines.append("|---|---|---|")
    meanings = {
        "live": "service-info fetched and valid",
        "auth_required": "reachable, returns 401/403 (needs a token)",
        "live_no_serviceinfo": "reachable but no valid service-info at known paths",
        "server_error": "5xx from the service",
        "client_error": "4xx (other than 401/403/404)",
        "unreachable": "DNS/connection/timeout failure (down or private)",
        "no_url": "no URL registered",
    }
    for v, c in verdicts.most_common():
        lines.append(f"| `{v}` | {c} | {meanings.get(v, '')} |")

    lines.append("\n## Services by type\n")
    lines.append("| Artifact | Live deployments |")
    lines.append("|---|---|")
    for a, c in artifacts.most_common():
        lines.append(f"| `{a}` | {c} |")

    lines.append("\n## Per-service detail\n")
    lines.append("| Artifact | Name | Org | Declared | Reported | Liveness | Auth | URL |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append("| {artifact} | {name} | {org} | {declared} | {reported} | "
                     "`{liveness}` | {auth} | {url} |".format(
                         **{k: (v if v is not None else "") for k, v in r.items()}))

    lines.append("\n## What this tells the design\n")
    lines.append("- Registered URLs are inconsistent; DRS entries often point at "
                 "`.../objects/` — the server strips this to recover the base.")
    lines.append("- Service-reported versions frequently differ from the registry's declared "
                 "version (reconciled and surfaced as a warning).")
    lines.append("- A meaningful fraction of services are unreachable, auth-gated, or "
                 "non-compliant — the server degrades gracefully and never crashes on one bad endpoint.\n")

    with open("docs/compatibility.md", "w") as f:
        f.write("\n".join(lines) + "\n")
    with open("docs/compatibility-raw.json", "w") as f:
        json.dump({"generated": ts, "verdicts": dict(verdicts), "artifacts": dict(artifacts),
                   "rows": rows}, f, indent=2, default=str)

    print(f"Wrote docs/compatibility.md — {len(services)} services")
    print("Verdicts:", dict(verdicts))
    print("Artifacts:", dict(artifacts))


if __name__ == "__main__":
    asyncio.run(main())
